name: Docker Build Test

on:
  push:
    branches:
      - master

jobs:
  docker:
    name: Docker build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: docker build -t lto_poc .
